"""empty message

Revision ID: 846a84fd4443
Revises: 13d01f25c666
Create Date: 2018-10-28 13:13:48.711843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846a84fd4443'
down_revision = '13d01f25c666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('flightinquiries', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('hotelinquiries', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('hotels', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('packages', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('IsArchived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'IsArchived')
    op.drop_column('tickets', 'IsArchived')
    op.drop_column('packages', 'IsArchived')
    op.drop_column('hotels', 'IsArchived')
    op.drop_column('hotelinquiries', 'IsArchived')
    op.drop_column('flightinquiries', 'IsArchived')
    op.drop_column('customers', 'IsArchived')
    # ### end Alembic commands ###
